name: Upscale-rs Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Add Yarn packages
      run: yarn
    - name: Build app
      run: yarn tauri build
    - name: Run tests
      run: cd src-tauri && cargo test
