name: Upscale-rs Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Create required dist folder
      run: mkdir dist
    - name: Run tests
      run: cd src-tauri && cargo test
